"""Registered pipeline agents (shared catalog for marketplace + API)."""

from __future__ import annotations

from contentos_shared.specialist_catalog import CREATIVE_AGENT_SPECIALIST_SUITES

AGENT_CATALOG: list[dict[str, str]] = [
    {
        "name": "trend_intelligence",
        "queue": "contentos.trend_intelligence",
        "description": "Padrões virais de memória + analytics para a pesquisa",
        "category": "intelligence",
        "tier": "v3",
    },
    {
        "name": "research",
        "queue": "contentos.research",
        "description": "Pesquisa tendências e assuntos virais",
        "category": "creative",
        "tier": "core",
    },
    {
        "name": "hook",
        "queue": "contentos.hook",
        "description": "Escolhe o melhor gancho (mistério, choque, curiosidade…)",
        "category": "creative",
        "tier": "v3",
        "specialist_suites": CREATIVE_AGENT_SPECIALIST_SUITES,
    },
    {
        "name": "script",
        "queue": "contentos.script",
        "description": "Cria roteiros de até 60 segundos",
        "category": "creative",
        "tier": "core",
        "specialist_suites": CREATIVE_AGENT_SPECIALIST_SUITES,
    },
    {
        "name": "script_review",
        "queue": "contentos.script_review",
        "description": "Revisa e melhora o roteiro antes das cenas",
        "category": "creative",
        "tier": "v3",
    },
    {
        "name": "emotion",
        "queue": "contentos.emotion",
        "description": "Pontua emoção, curiosidade, retenção e impacto",
        "category": "creative",
        "tier": "v3",
    },
    {
        "name": "content_score",
        "queue": "contentos.content_score",
        "description": "Calcula nota geral 0-100 a partir de qualidade, retenção, emoção e sinais virais",
        "category": "quality",
        "tier": "v4",
    },
    {
        "name": "content_intelligence",
        "queue": "contentos.content_intelligence",
        "description": "Score viral + sugestões de reuso antes das cenas (V4)",
        "category": "intelligence",
        "tier": "v4",
    },
    {
        "name": "video_review",
        "queue": "contentos.video_review",
        "description": "Nota criativa do vídeo e sugestões de melhoria",
        "category": "quality",
        "tier": "v3",
    },
    {
        "name": "auto_retry",
        "queue": "contentos.auto_retry",
        "description": "Checkpoint de retry criativo com orçamento e rewind controlados pelo workflow",
        "category": "quality",
        "tier": "v4",
    },
    {
        "name": "scene",
        "queue": "contentos.scene",
        "description": "Divide roteiro em cenas",
        "category": "creative",
        "tier": "core",
        "specialist_suites": CREATIVE_AGENT_SPECIALIST_SUITES,
    },
    {
        "name": "storyboard",
        "queue": "contentos.storyboard",
        "description": "Plano visual por cena (enquadramento, movimento, transições)",
        "category": "creative",
        "tier": "v3",
    },
    {
        "name": "scene_director",
        "queue": "contentos.scene_director",
        "description": "Traduz storyboard em parâmetros FFmpeg (zoom, pan, ritmo)",
        "category": "creative",
        "tier": "v3",
    },
    {
        "name": "clip_research",
        "queue": "contentos.clip_research",
        "description": "Pesquisa B-roll via Content Sources (V2)",
        "category": "assets",
        "tier": "v2",
    },
    {
        "name": "asset_collector",
        "queue": "contentos.asset_collector",
        "description": "Coleta e indexa clips (V2)",
        "category": "assets",
        "tier": "v2",
    },
    {
        "name": "media_analyze",
        "queue": "contentos.media_analyze",
        "description": "Análise visual IA + embeddings para biblioteca de assets (V5.0.3)",
        "category": "assets",
        "tier": "v5",
    },
    {
        "name": "asset_search",
        "queue": "contentos.asset_search",
        "description": "Busca os melhores assets indexados para cada cena",
        "category": "assets",
        "tier": "v2",
    },
    {
        "name": "takes",
        "queue": "contentos.takes",
        "description": "Seleciona takes do Asset Manager",
        "category": "production",
        "tier": "core",
    },
    {
        "name": "voice",
        "queue": "contentos.voice",
        "description": "Narração via Speech Provider (Piper)",
        "category": "production",
        "tier": "core",
    },
    {
        "name": "subtitle",
        "queue": "contentos.subtitle",
        "description": "Legendas via Whisper local",
        "category": "production",
        "tier": "core",
    },
    {
        "name": "editor",
        "queue": "contentos.editor",
        "description": "Montagem FFmpeg 1080x1920 60fps",
        "category": "production",
        "tier": "core",
    },
    {
        "name": "quality",
        "queue": "contentos.quality",
        "description": "Validação de qualidade",
        "category": "quality",
        "tier": "core",
    },
    {
        "name": "publisher",
        "queue": "contentos.publisher",
        "description": "Prepara metadados de publicação",
        "category": "publish",
        "tier": "core",
    },
    {
        "name": "multi_content",
        "queue": "contentos.multi_content",
        "description": "Gera thread X, LinkedIn, newsletter, SEO e email a partir do roteiro (V4.2)",
        "category": "intelligence",
        "tier": "v4",
    },
    {
        "name": "multi_content_video",
        "queue": "contentos.multi_content_video",
        "description": "Variantes TikTok, YouTube Shorts e Instagram Reels do mesmo render (V4.2)",
        "category": "intelligence",
        "tier": "v4",
    },
    {
        "name": "thumbnail",
        "queue": "contentos.thumbnail",
        "description": "Gera thumbnail vertical (V2 async)",
        "category": "assets",
        "tier": "v2",
    },
    {
        "name": "analytics",
        "queue": "contentos.analytics",
        "description": "Análise IA pós-publicação (V2 async)",
        "category": "intelligence",
        "tier": "v2",
    },
    {
        "name": "learning",
        "queue": "contentos.learning",
        "description": "Aprendizado pós-pipeline → Memory + KB (V4.2)",
        "category": "intelligence",
        "tier": "v4",
    },
    {
        "name": "knowledge_base",
        "queue": "contentos.knowledge_base",
        "description": "Indexa artefatos do pipeline na base permanente e atualiza o content graph",
        "category": "intelligence",
        "tier": "v4",
    },
    {
        "name": "creative_memory",
        "queue": "contentos.creative_memory",
        "description": "Merge KB + Learning em memória criativa unificada (V5.2.5)",
        "category": "intelligence",
        "tier": "v5",
    },
]
