"""Niche keyword signals for specialist matching."""

from __future__ import annotations

NICHE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "gaming": (
        "gaming",
        "games",
        "game",
        "jogos",
        "jogo",
        "gamer",
        "esports",
        "e-sports",
        "gta",
        "minecraft",
        "fortnite",
        "playstation",
        "xbox",
        "nintendo",
        "steam",
        "boss",
        "speedrun",
        "gameplay",
    ),
    "technology": (
        "tech",
        "technology",
        "tecnologia",
        "software",
        "hardware",
        "inteligência artificial",
        "inteligencia artificial",
        " ia ",
        "chatgpt",
        "programação",
        "programacao",
        "dev",
        "startup tech",
        "smartphone",
        "android",
        "iphone",
        "chip",
        "nvidia",
    ),
    "business": (
        "business",
        "negócios",
        "negocios",
        "empreendedorismo",
        "empreendedor",
        "marketing",
        "vendas",
        "funil",
        "roi",
        "lucro",
        "marca",
        "b2b",
        "b2c",
        "growth",
        "estratégia",
        "estrategia",
    ),
}

NICHE_ALIASES: dict[str, str] = {
    "games": "gaming",
    "game": "gaming",
    "jogos": "gaming",
    "jogo": "gaming",
    "gamer": "gaming",
    "tech": "technology",
    "tecnologia": "technology",
    "negocios": "business",
    "negócios": "business",
    "empreendedorismo": "business",
    "marketing": "business",
}
