apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: contentos
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: contentos
spec:
  replicas: 2
