apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: contentos-secrets
  namespace: contentos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: contentos-aws-sm
  target:
    name: contentos-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: contentos/production
        property: JWT_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: contentos/production
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: contentos/production
        property: REDIS_URL
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: contentos/production
        property: MINIO_SECRET_KEY
