apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: contentos

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - gateway.yaml
  - workflow-engine.yaml
  - agents-worker-pools.yaml
  - ai-gateway.yaml
  - dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: contentos
  app.kubernetes.io/managed-by: kustomize
